### ISSUE TITLE
citra-emu/citra GPL violation

### ISSUE THREAD

**Issue by cobalt2727** [Lemonade-emu/Lemonade#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

all

### Description of Issue

There are, quite literally, [hundreds of thousands of uncredited lines of code in this repository right now](https://github.com/Lemonade-emu/Lemonade/commit/9289b445f949eb8b03e5192956d755271f4057b8). This is not an exaggeration.
I made no contributions to the original codebase so this doesn't affect me, but I would strongly suggest cleaning up your git history if you want people to take your project seriously.

### Expected Behavior

Same as https://github.com/Lemonade-emu/Lemonade/issues/97 - follow the license, properly credit the developers that did 99% of the work on this repository. Fix the git history. I have attached some documentation as a starting point: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo

### Reproduction Steps

N/A

### Log File

N/A

### System Configuration

N/A

**Comment by Ishan09811** [comment]
@cobalt2727 
![Screenshot_20240411-234815](https://github.com/Lemonade-emu/Lemonade/assets/156402647/6e8f93cd-b6e2-4473-acff-e92bb41e1767)

**Comment by nyaaaaaaaaaaaaaaaaaaaaaaaaaaaaa420** [comment]
nyaaaaaaaaaaaaaaaa :3 you guys done removed credits for 200k lines of code by not properly preserving the commit history...
make a catgirl sad :(

**Comment by cobalt2727** [comment]
I'm glad you pointed that out.
Look at that repository - it hasn't had any commits in **five years**.
This repository is based on modern Citra, though - which is exactly my point. This repository _doesn't even use the repo it's forked off of as a base_.

Do you see how disorganized this is, now?

Good luck trying to hunt down the cause of any glitches caused by commits from before you forked anything. With most of the mainstream emulators, users can report "hey, I found a bug, and I can download/build an older version that works fine. Here is the exact change that caused the problem."
Your codebase makes that physically impossible to do.

Unless you want to constantly be using other Citra forks as a reference in the future, you need to get this fixed.

**Comment by nyaaaaaaaaaaaaaaaaaaaaaaaaaaaaa420** [comment]
I nyagree, it would feel very bad to have my code in a big project like this without being acknowled for it ...

**Comment by Ishan09811** [comment]
@cobalt2727 
first of all We haven't deleted the commit history and why would we? btw this is the same repo used for ``citra-enhanced`` because we had to make an initial commit to switch it to the latest ``citra-canary`` code but the commit history is gone.
but we will try to recover the commit history

**Comment by cobalt2727** [comment]
Prior to the mainline Citra takedown, you have an unrelated commit history from another random Citra fork called Citra-Enhanced, last I checked. The actual commit history was, yes, **_deleted_** when Gamer64 copy/pasted the raw source files in without preserving the commits themselves.

**Comment by cobalt2727** [comment]
Both Pablo's fork of Citra and Lime3DS did this correctly. You guys have a broken repo right now from attempting to just shove a new codebase in on top of an older one, rather than properly creating a new fork.

**Comment by vabold** [comment]
> @cobalt2727 first of all We haven't deleted the commit history and why would we? btw this is the same repo used for `citra-enhanced` because we had to make an initial commit to switch it to the latest `citra-canary` code but the commit history is gone. but we will try to recover the commit history

https://github.com/Lemonade-emu/Lemonade/commit/9289b445f949eb8b03e5192956d755271f4057b8

This is what deleting the commit history looks like for future reference.

`git rebase` is how you rebase a repository while preserving the commit history.

**Comment by cobalt2727** [comment]
@Ishan09811 Please reopen this if you want the project to be taken seriously. The problems raised above are still an issue.
