### ISSUE TITLE
Got an issue with pull requests

### ISSUE THREAD

**Issue by JaffaCat** [Lemonade-emu/Lemonade#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Latest build

### Description of Issue

Hi developers,

Was attempting to suggest a PR to be merged, but this bug keeps happening. It is a bit frustrating, as the PR would have helped improve the emulator. Hopefully you can fix the issue or reach out to Phil from Michaelsoft, as this PR could help improve the emulator in a number of different ways

Kind regards,
dee snuts

### Expected Behavior

The ability to comment on PR's work as intended.

### Reproduction Steps

![image](https://github.com/Lemonade-emu/Lemonade/assets/134164477/dee03e6e-10e4-4e3e-bd70-aebb62eb4d8a)

### Log File

https://web.archive.org/web/20240411210153/https://github.com/Lemonade-emu/Lemonade/pull/101

### System Configuration

Sorry, I'm not very good with computers, how do I check? I got stuck on the bit where it asks me to use a browser.

**Comment by JaffaCat** [comment]
Fixed it.

**Comment by JaffaCat** [comment]
Fixed.

**Comment by Gamer64ytb** [comment]
Stop.

**Comment by Litbolt123** [comment]
wait, really? they work now? :O
