### ISSUE TITLE
zelda ocarine has video and sound lag

### ISSUE THREAD

**Issue by Juan1980zero** [Lemonade-emu/Lemonade#23]

**Comment by kleidiss** [comment]
Sprcs?

**Comment by Gamer64ytb** [comment]
I tested zelda ocarina and runs fine, what specs you have?

**Comment by Juan1980zero** [comment]
Ah, I checked again and if it works there was a slight lag due to the shaders, I don't know what happened the first time I used it, like something in the buffer was wrong that made almost everything unstable, it works fine on my 8GB helio g99 " "Maybe how I restarted the problem would be fixed."
