### ISSUE TITLE
Crash when launching a game

### ISSUE THREAD

**Issue by Someguy1519** [Lemonade-emu/Lemonade#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

4982761 and newer builds

### Description of Issue

Lemonade crashes when launching a game on any build from 4982761 onwards

### Expected Behavior

Lemonade doesn't crash when launching a game.

### Reproduction Steps

Try to launch a game in Lemonade and wait a little bit.

### Log File

[lemonade_log.txt.old.txt](https://github.com/Lemonade-emu/Lemonade/files/14786425/lemonade_log.txt.old.txt)
[lemonade_log.txt](https://github.com/Lemonade-emu/Lemonade/files/14786429/lemonade_log.txt)

Vulkan logs:

[lemonade_log.txt](https://github.com/Lemonade-emu/Lemonade/files/14786504/lemonade_log.txt)
[lemonade_log.txt.old.txt](https://github.com/Lemonade-emu/Lemonade/files/14786505/lemonade_log.txt.old.txt)

### System Configuration

CPU: Snapdragon 8 Gen 1 (Galaxy S22+)
GPU/Driver: Adreno 730 stock driver (also affects Vulkan with stock driver and Turnip 24.1.0 R18)
RAM: 8GB
OS: Android 14

**Comment by Ishan09811** [comment]
This issue is fixed in newer actions build but it's recommended to use latest releases builds as releases builds are stable but actions build may unstable
