### ISSUE TITLE
Builds Fail on Arch (CachyOS)

### ISSUE THREAD

**Issue by SolarNyan** [Lemonade-emu/Lemonade#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Alpha

### Description of Issue

After attempting to build from source, both release and debug builds are currently failing on Arch. Things seem to go fine until the final step of linking the QT and SDL executables. Build fails with the following log: https://pastebin.com/Qva7Dat9

After these two steps fail, only the Lemonade-Room executable is built.

Anyone else running into this issue? I cloned the repo recursively and also have every dependency on Arch installed.

### Expected Behavior

Build outputs proper SDL and QT executables.

### Reproduction Steps

Follow the build guide on the wiki while building on Arch and Arch derivatives. 

### Log File

[log.txt](https://github.com/Lemonade-emu/Lemonade/files/14817828/log.txt)

### System Configuration

OS: CachyOS (Arch derivative)

**Comment by dnmodder** [comment]
I use CachyOS and have had no problems compiling from source or using the AUR package (which I created myself).

**Comment by SolarNyan** [comment]
> I use CachyOS and have had no problems compiling from source or using the AUR package (which I created myself).

After looking into it some more, it seems like the root of the failure was the CMake file's default configurations: I compare the default file that generates from the commands on the build wiki with your AUR package, and the default CMake file doesn't seem to use any system versions of dependencies, which seem to be needed. There's also certain build settings are also unchecked as well.

Thank you for informing me of your AUR package! I probably would've never figured this out without it.
