### ISSUE TITLE
MacOS Build ?

### ISSUE THREAD

**Issue by Defaalt** [Lemonade-emu/Lemonade#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

MacOS build

### Description of Issue

The MacOS build is broken.

### Expected Behavior

Working build

### Reproduction Steps

Broken build.

### Log File

No log file. 

### System Configuration

CPU: M1
GPU/Driver: M1
RAM: 8gb
OS: MacOS 14

**Comment by Ishan09811** [comment]
@Azyz-raw 
Can you provide more information ? 
and we also knew that it may broken as we don't have any testers of macos build for now

**Comment by Azyz-raw** [comment]
The latest release is broken. But the nightly build i got this morning is working. I'll ping you on discord. Willing to help !

**Comment by kleidiss** [comment]
Ah there was a problem on the release zip , ill close the issue and upload a new mac os universal zip

**Comment by venlol** [comment]
it says can't be verified by developers
