### ISSUE TITLE
Help > FAQ opens FAQ page for old base

### ISSUE THREAD

**Issue by atlas1337** [Lemonade-emu/Lemonade#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly

### Description of Issue

When selecting Help > FAQ it opens a web page for the old base

### Expected Behavior

It would be expected for it to open to the new base

### Reproduction Steps

Click help
Click FAQ

### Log File

N/A

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by kleidiss** [comment]
I forgot to change that . I'll look at it for the next release

**Comment by atlas1337** [comment]
Sounds good! Figured I would open an issue about it in case you weren't aware.

**Comment by kleidiss** [comment]
For now, it's removed because it has no use
