### ISSUE TITLE
Can you also do a PC version

### ISSUE THREAD

**Issue by ryzendew** [Lemonade-emu/Lemonade#6]
i have found no one to take over citra on pc yet and you guys seem to know what you are doing

**Comment by Miguel-hrvs** [comment]
For citra on pc we have Pablo's branch. I'll compare both of them performance wise.

**Comment by 73CC** [comment]
Would be awesome

**Comment by kleidiss** [comment]
I managed to compile the canary relelase version on Windows , Maybe i relelase it once im done removing the old brand

**Comment by Justin-ojay** [comment]
Ok nice, is it possible for you guys to bring multiplayer to mobile, it's not necessary but I'm curious if you'll consider doing it

**Comment by kleidiss** [comment]
Since we have pc builds in workflows now, i will close the issue

It still needs a few fixes, but it's done
