### ISSUE TITLE
mvsc vs msys2 build

### ISSUE THREAD

**Issue by 7zxkv** [Lemonade-emu/Lemonade#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2.1 alpha

### Description of Issue

hello, 
I'm sorry to open this discussion, but just to be clear, which build do you prefer between the two (recommended)?

best regards

### Expected Behavior

-

### Reproduction Steps

-

### Log File

-

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

**Comment by kleidiss** [comment]
If the builds work right, they should be the exact same , I use MSVC
