### ISSUE TITLE
Save states can't be loaded

### ISSUE THREAD

**Issue by jmbyers117** [Lemonade-emu/Lemonade#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

72caae0

### Description of Issue

When I try to use save states, I'm able to create a save state, and I can see the cst file in my states folder. When I go to load a save state though, it lists no saves and doesn't allow me to load any. It's as if it can't see any files in the states folder. 

### Expected Behavior

The ability to save and load save states. 

### Reproduction Steps

I'm using my phone, Google pixel 6 pro. Simply trying to load a save state should reproduce it. 

### Log File

No log associated.

### System Configuration

CPU: 
GPU/Driver: 
RAM: 
OS: android 14

Google pixel 6 pro

**Comment by JaffaCat** [comment]
Save states are in the process of being scrapped, they may not work while the changes are being made.
