### ISSUE TITLE
Swap screens button for touchscreen  controls/ Feature request

### ISSUE THREAD

**Issue by HJMBgit84** [Lemonade-emu/Lemonade#9]
Could you please include a Swap screens button on the touchscreen controls please? I requested this to the citra team but don't know why they did not include it :(

**Comment by Ishan09811** [comment]
@HJMBgit84 
I am closing your request as your requested option is already present in this lemonade emulator 
![Screenshot_20240323-132456](https://github.com/Gamer64ytb/Lemonade/assets/156402647/9fe993c2-c771-4d39-aae0-afd4fa7f40a9)

**Comment by HJMBgit84** [comment]
If you read my request It is not in the configuration, I mentioned that it is a swap screens button on touchscreen controls, an additional button on screen like home button that citra had added on the touchscreen controls.

**Comment by Ishan09811** [comment]
you can directly open the drawer and swap screen so why would we add a option in touch screen controls which will be not good and we will also revert the ui to old Citra ui so may we will think about your opinion later but not now.

**Comment by HJMBgit84** [comment]
Ok thanks anyway for taking the time to reply to my messages.

**Comment by Gamer64ytb** [comment]
Not a bad idea to be honest. Ill look about It as soon as I get how touch controls work 🙂

**Comment by Gamer64ytb** [comment]
I can combine It with a 2x speed option too, so we can squash the feature more to not look useless. Like mmj did with the home button maybe

**Comment by HJMBgit84** [comment]
Thanks for take it into consideration, appreciate a lot your opinion 🤠 thanks

**Comment by Gamer64ytb** [comment]
I'll try add this today.

**Comment by HJMBgit84** [comment]
Amazing 😍 thank you so much, btw my native language is Spanish too but I am from Central America, Costa Rica, thanks for considering my enhancement suggestion.

**Comment by Gamer64ytb** [comment]
yo también hablo español nativo, así que genial entonces jajajjaaj. Ya he implementado lo que has pedido, sólo me queda probar si funciona

**Comment by Gamer64ytb** [comment]
listo, he testeado esto en mi teléfono mis cambios y todo parece ir correctamente. https://github.com/Lemonade-emu/Lemonade/commit/5e66187ea95684ee2ed4cc960d0660e8ce10e2b7

**Comment by HJMBgit84** [comment]
Genial ..! No puedo esperar para probarlo en el next release 😎, te lo agradezco mucho y te deseo los mejores éxitos con lemonade 🍋
