### ISSUE TITLE
Save State

### ISSUE THREAD

**Issue by Litbolt123** [Lemonade-emu/Lemonade#94]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Would it be possible to have Save States working? There is a button for it but it seems that it is not able to load any states or see that there is a slot taken up by a save state.

I am on Windows 11 and have a good gaming laptop.

### Why would this feature be useful?

This would make lemonade better for various games. It would allow you to walk away from it anytime and return whenever you like as well.

**Comment by Litbolt123** [comment]
Ok, thanks!

**Comment by Skyrimer3d** [comment]
Terrible news, i'll stick with first emu release and ignore the rest, save states are too important for me.
